version: '3.8'

services:
  prod:
    container_name: folham-api
    image: folham-api-image:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['node', 'dist/main.js']
    ports:
      - 3010:3010
      - 9229:9229
    networks:
      - folham-network
    volumes:
      - ./dist:/app/dist
    restart: unless-stopped
    environment:
      NODE_ENV: production

networks:
  folham-network:
