name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Cache Dependencies
        uses: c-hive/gha-yarn-cache@v2
      - name: Install yarn
        run: npm install --global yarn
      - name: Install Dependencies
        run: rm -rf node_modules && yarn
      - name: Run tests
        run: yarn test
      - name: Run build test
        run: yarn build
