name: Deploy to Production Azure

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: myitura.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build, tag, and push image to Azure Container Registry
        run: |
          docker build -t myitura.azurecr.io/folham-api:folham_api_image_production .
          docker push myitura.azurecr.io/folham-api:folham_api_image_production
